### ISSUE TITLE
Bugreport

### ISSUE THREAD

**Issue by Knollewurz** [geraldmwangi/GuitarSynth-DPF#4]
Thank you, great idea, compiles fine but Ardour does`t load, gives erros while scanning...
PluginManager Output:
[Info]: Scanning: /home/user/.vst/GuitarSynth-vst.so
[ERROR]: Could not load VST2 plugin '/home/user/.vst/GuitarSynth-vst.so': /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: g_settings_schema_list_keys
[WARNING]: Cannot open VST2 module '/home/user/.vst/GuitarSynth-vst.so'
Scan Failed.

ArdourLogOutput:
2021-11-24T14:46:05 [ERROR]: LV2: Failed to instantiate plugin http://github.com/geraldmwangi/GuitarSynth
ladspa and vst do not appear  at all in Pluginmanager

Hope this is useful
best regards
knollewurz

**Comment by geraldmwangi** [comment]
hi.Have you tried carla as a host? I havent worked on this for quite
some time but the last time it worked with carla.GeraldOn Wed, 2021-11-
24 at 05:49 -0800, Knollewurz wrote:

**Comment by geraldmwangi** [comment]
I'm working currently on GuitarMidi-lv2 (https://github.com/geraldmwangi/GuitarMidi-LV2) which extracts midi notes from a guitar signal in a polyphonic fashion. I'm making good progress there, so watch that repo
